apiVersion: v1
kind: ConfigMap
metadata:
  name: kh-frontend-html
data:
  index.html: | 
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Milestone 2</title>
      </head>
      <body>
        <h1><span id="user"></span> has reached milestone 2!</h1>
        
        <p>Dit is het container ID: <span id="container-id"></span></p>
        
        

        <script>
          // fetch user from API
          fetch("/api/users")
            .then((res) => res.json())
            .then((data) => {
              // get user name
              //const user = data.name; gebruiken bij python dictonary
              const user = data[0];
              // display user name
              document.getElementById("user").innerText = user;
            });

          // Fetch Container ID van de API
          fetch("/api/container-id")
            //omzetten van de response van de API server (=python dictonary) naar een javascript object
            .then((res) => res.json())
            //Data uitpakken, de waarde opvragen van die speciefieke key-value.
            .then((data) => {
            // We pakken de 'container_id' uit de JSON die de API teruggeeft
              const containerId = data.container_id;
            // We zetten dit in een HTML element met id="container-id"
              document.getElementById("container-id").innerText = containerId;
            })
            .catch((err) => console.error("Fout bij ophalen container ID:", err));




        </script>
      </body>
    </html>