apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'fastapi-app'
        # We vertellen Prometheus expliciet waar de metrics staan
        metrics_path: '/api/metrics' 
        static_configs:
          # Hier gebruiken we de DNS naam van je Kubernetes service
          # Formaat: <service-naam>.<namespace>:<poort>
          # Omdat kh-api in de 'default' namespace staat en prometheus in de namespace 'monitoring':
          - targets: ['kh-api.default.svc.cluster.local:8000']